# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "customized-bundle-app"
client_id = "e2f0ab17f48371397964d6a6220a4c62"
application_url = "https://infant-generated-permanent-aluminum.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://infant-generated-permanent-aluminum.trycloudflare.com/auth/callback",
  "https://infant-generated-permanent-aluminum.trycloudflare.com/auth/shopify/callback",
  "https://infant-generated-permanent-aluminum.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shop-chopper-demo.myshopify.com"
